### ISSUE TITLE
Feature request: updateFvarLabels and updateSampleNames

### ISSUE THREAD

**Issue by lmsimp** [lgatto/Features#167]
Are there equivalents of the above `MSnbase` functions in `QFeatures` to allow users to update the `rownames` and `colnames` of SE or QF objects?

**Comment by lgatto** [comment]
No, there aren't, and I am not sure they are needed. These functions were necessary in `MSnbase` due to the way `combine()` worked: it looked at the feature/row and sample/column names to define how to merge two `MSnSet` and the respective `fData` columns. It was thus important to be able to easily set these. In `QFeatures`, the relation between samples of different assays within a `QFeatures` has become explicit (and encoded in the `colData` - see issue #168) and shared but inconsistent `rowData` variables are simply dropped (I believe an error was thrown in `MSnbase`, hence the need for an easy hack with `updateFvarLabels()`) but still available in the parent assays. 

Hope this clarifies the reasons, but feel free to provide a use case if you think such helper functions are still required.

**Comment by lmsimp** [comment]
Thanks for getting back to me Laurent, closing this issue for now.
