### ISSUE TITLE
colData is not updated in SE objects when aggregating across levels

### ISSUE THREAD

**Issue by lmsimp** [lgatto/Features#168]
I wish to add some experiment data to the `colData` slot of an SE inside a QF object as per the below. After using `aggregateFeatures` the `colData` is not maintained - has this been intentionally programmed this way to remove it? Would it be feasible or practical to have an argument passed to `aggregateFeatures` to allow users to keep this information as you aggregate through the data levels?

```r
library("QFeatures")
data(hlpsms)

## read data
hl <- readQFeatures(hlpsms, ecol = 1:10, name = "psms")

## add pdata
colData(hl[["psms"]])$Tag <- colnames(hl[["psms"]])

## aggregate to peps
hl <- aggregateFeatures(hl, "psms", "Sequence", name = "peptides", fun = colMeans)
hl <- aggregateFeatures(hl, "peptides", "Sequence", name = "proteins", fun = colMeans)

colData(hl[["psms"]])
```
DataFrame with 10 rows and 1 column
              Tag
      <character>
X126         X126
X127C       X127C
X127N       X127N
X128C       X128C
X128N       X128N
X129C       X129C
X129N       X129N
X130C       X130C
X130N       X130N
X131         X131

```r
colData(hl[["peptides"]])
```
DataFrame with 10 rows and 0 columns 

```r
colData(hl[["proteins"]])
```
DataFrame with 10 rows and 0 columns

**Comment by lgatto** [comment]
Hi Lisa - indeed, they aren't because once you work with a `QFeatures` object, it's that `colData` that is relevant. The individual assays' `colData` become irrelevant. Think of a situation where you add a new assay with different samples - all sample metadata needs to be handled centrally, which is done at the `QFeatures` level. In your case, you would set the `Tag` annotation in `colData(hl)`. 

```r
> library("QFeatures")
> data(hlpsms)
> hl <- readQFeatures(hlpsms, ecol = 1:10, name = "psms")
> hl$Tag <- colnames(hl[["psms"]])
> hl$Tag
 [1] "X126"  "X127C" "X127N" "X128C" "X128N" "X129C" "X129N" "X130C" "X130N"
[10] "X131" 
> hl <- aggregateFeatures(hl, "psms", "Sequence", name = "peptides", fun = colMeans)
> hl <- aggregateFeatures(hl, "peptides", "Sequence", name = "proteins", fun = colMeans)
```
If you them want to extract an assay and recover its relevant `colData`, you would use `getWithColData()`, that will extract the information for samples relevant of that specific assay:

```r
> colData(getWithColData(hl, 2)) 
DataFrame with 10 rows and 1 column
              Tag
      <character>
X126         X126
X127C       X127C
X127N       X127N
X128C       X128C
X128N       X128N
X129C       X129C
X129N       X129N
X130C       X130C
X130N       X130N
X131         X131
Warning message:
'experiments' dropped; see 'metadata' 
```

**Comment by lmsimp** [comment]
Thanks @lgatto makes sense.
